name: ESLint

on:
  pull_request:
    types: [opened, edited]

jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code 🚚
        uses: actions/checkout@v3

      - name: Setup node Env 🧩
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install Packages 🚢
        run: yarn

      - name: Run the linter
        run: yarn lint
